#!/bin/bash
# Check for xwinwrap and mpv
array=( "xwinwrap" "mpv" "xrandr" )

for i in "${array[@]}"
do
    command -v $i >/dev/null 2>&1 || { 
        echo >&2 "$i required"; 
        exit 1; 
    }
done

if [ $# == 0 ] ; then
    echo "Usage: mpvwall.sh wallpaper_file"
    exit 1;
fi

Xaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
Yaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

xwinwrap -ov -g ${Xaxis}x${Yaxis}+0+0 -- mpv -wid WID $1 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-input-default-bindings
